#
# Site settings
#
title: Neeraj Karamchandani
description: Security Researcher | Ph.D. Candidate, Penn State
author: Neeraj Karamchandani
email: gourmet.fir_6i@icloud.com
github_username: neerajkaram
linkedin_username: karamchandani

# URL
url: https://neerajkaram.github.io
baseurl: ""

avatar: /images/NKs.png

# Navigation
navigation:
  - title: About
    url: /about
  - title: Research
    url: /research
  - title: Projects
    url: /projects

# Build
permalink: /:title/
version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
